### PR TITLE
fix: Show doubly nested definitions

### LINKED ISSUE #234: Definitions under `outline.entry` are missing in the website
### 対象ドキュメント

```typst
#show outline.entry: it => link(
  it.element.location(),
  it.indented(it.prefix(), it.inner()),
)
```

`entry` is a definition under the `outline` scope, and it also has [a few definitions (typst.app/docs)](https://typst.app/docs/reference/model/outline/#definitions-entry-definitions), namely, `outline.entry.{indented,prefix,inner}`.

### 問題

However, definitions under `outline.entry` are [missing in typst-jp](https://typst-jp.github.io/docs/reference/model/outline/). The last paragraph on this page is the `fill` parameter of `outline.entry`.

As shown below, our templates only handle a single level of scope, and ignore definitions in definition.

```shell
$ cd website/src
$ rg scope
utils/isPageOfKind.test.ts
51:                                     scope: [],
121:                                    scope: [],
183:                                    scope: [],
227:                                            scope: [],

types/model.ts
81:     scope: Func[];
122:            scope: Func[];

components/templates/TypeTemplate.tsx
53:                     {content.scope.length > 0 && (
60:                                     {content.scope.map((method, index) => (

components/templates/FuncTemplate.tsx
73:                     {content.scope.length > 0 && (
80:                                     {content.scope.map((method, index) => (
```

<details>
<summary>Screenshot of the outline (as a JSON field) of outline (as the element) in docs.json</summary>

</details>

<details>
<summary>Screenshot of bodies of outline in docs.json</summary>

</details>

### 改善案

Considering that this page have not been translated, and ~~the official typst-docs also has a bug about it~~, I suggest doing nothing for the time being and dealing with it later.
https://github.com/typst/typst/issues/6135

**Update**: The bug in typst-docs has been fixed in typst/typst#6684.

### 貢献意思

- [x] このIssueを解決するPull Requestの作成を自身で希望する場合はチェックしてください。

### PR DESCRIPTION
**Pull request by YDX-2147483647**
This PR will uncover _doubly_ nested definitions, which were previously hidden.
Resolves #234

## Example

1. `outline` is a function.
2. `outline.entry` is a function nested in `outline`
3. [`outline.entry.indented`](https://typst.app/docs/reference/model/outline/#definitions-entry-definitions-indented) is a function doubly nested in `outline`.

Currently, `indented`, `prefix`, and other definitions under `outline.entry` are missing in https://typst-jp.github.io/docs/reference/model/outline/. The last part on that page is `fill`, which is a parameter of `outline.entry`.

This PR will add those definitions.

## Preview

- Official: https://typst.app/docs/reference/model/outline/
  

- Before: https://typst-jp.github.io/docs/reference/model/outline/
  

- After (preview with the upstream English dev docs): https://688e4447b70c7f0008cf9ff5--ydx-typst.netlify.app/docs/reference/model/outline/
  

### ~~Please check the translation~~ https://github.com/typst-jp/typst-jp.github.io/pull/238#discussion_r2250468953

> [Definitions of `entry`](https://typst.app/docs/reference/model/outline/#definitions-entry-definitions) 

LLM and translators suggest:

> `entry`の定義

In Chinese, `entry`<ins>**下**</ins>的定義 is better (的 = の). But in Japanese, I don't know…

### The scope has at most two levels

You can verify it by searching `assets/docs.json` with [ripgrep](https://github.com/BurntSushi/ripgrep).

```bash
$ rg '"scope": \[$' docs.json --after-context 3
…
--
13505:                "scope": [
13506-                  {
13507-                    "path": [
13508-                      "outline"
--
13571:                    "scope": [
13572-                      {
13573-                        "path": [
13574-                          "entry"
--
13967:                "scope": [
13968-                  {
13969-                    "path": [
13970-                      "par"
--
14925:                "scope": [
14926-                  {
14927-                    "path": [
14928-                      "table"
…
```

### There are still broken links due to an upstream bug

In the section [_Styling the outline > Building an Entry_](https://typst.app/docs/reference/model/outline/#building-an-entry), the links to `indented`, `prefix`, and `inner` all point to `outline.entry`, but they are expected to point to `outline.entry.{indented,prefix,inner}`, respectively.

These links are generated by typst-docs, and can hardly be fixed here.
I've [fixed](https://github.com/typst/typst/pull/6684) [the bug](https://github.com/typst/typst/issues/6135) in the upstream, but it won't take effect before typst-jp merges the uptream.
Considering that this page has not been translated yet, you can deal with this issue later.

In spite of it, links in 目次 and 引数 will behave normally, as they are generated by typst-jp.

### CODE REVIEW

**Review by ultimatile — APPROVED** [review]

**Review by kimushun1101 — APPROVED** [review]
It worked fine on the `outline` page. LGTM!

File: website/src/components/templates/FuncTemplate.tsx [hunk 1]
```diff
@@ -70,57 +70,88 @@ export const FuncTemplate: FC<FuncTemplateProps> = ({
...
+	// To be consistent with the official typst.app/docs,
+	// the following heading levels will _not_ increase with the scope level.
+	return (
+		<div class="mt-8">
+			<h2 id={`${parentId}definitions`} class="flex items-baseline gap-1">
+				{parent ? (
+					// Currently, the scope has at most two levels.
+					// Therefore, it is sufficient to only annotate the direct `parent`.
+					<>
+						<code>{parent.name}</code>の定義
```
Comment (YDX-2147483647) [inline website/src/components/templates/FuncTemplate.tsx:102]: Did you notice the new Japanese phrase `entry`の定義 here? Should it be `entry`<ins>**下**</ins>の定義?

(This section will describe `outline.entry.indented`, `outline.entry.prefix`, and other `outline.entry.*`, but will not describe `outline.entry`.)

Comment (ultimatile) [reply website/src/components/templates/FuncTemplate.tsx:102]: More precisely, it should be “associated definitions of entry” (Japanese: entryの関連定義).
Assuming associated definitions also serve as definitions of entry, using “entryの定義” is acceptable.
Readers may encounter the actual definition of “entry” before the heading “entryの定義,” and this may not confuse them.

**Review by 3w36zj6 — APPROVED** [review]
LGTM, thanks!
